"""Tests for the stub generator module."""

from __future__ import annotations

from pathlib import Path

from capnp_stub_gen.generator import StubGenerator


class TestStubGeneratorInit:
    """Tests for StubGenerator initialization."""

    def test_init_with_path_string(self, simple_schema_path: Path) -> None:
        """Generator should accept string path."""
        generator = StubGenerator(str(simple_schema_path))
        assert generator.schema_path == simple_schema_path

    def test_init_with_path_object(self, simple_schema_path: Path) -> None:
        """Generator should accept Path object."""
        generator = StubGenerator(simple_schema_path)
        assert generator.schema_path == simple_schema_path


class TestStubGeneratorSimpleSchema:
    """Tests for generating stubs from a simple schema."""

    def test_generate_stub_returns_string(self, simple_schema_path: Path) -> None:
        """generate_stub should return a string."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()
        assert isinstance(result, str)
        assert len(result) > 0

    def test_stub_contains_header(self, simple_schema_path: Path) -> None:
        """Generated stub should contain proper header."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert '"""Type stubs for simple Cap\'n Proto schema.' in result
        assert "Auto-generated by capnp-stub-gen" in result
        assert "from __future__ import annotations" in result

    def test_stub_contains_reader_class(self, simple_schema_path: Path) -> None:
        """Generated stub should contain Reader classes."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "class PersonReader:" in result
        assert "class AddressReader:" in result

    def test_stub_contains_builder_class(self, simple_schema_path: Path) -> None:
        """Generated stub should contain Builder classes."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "class PersonBuilder:" in result
        assert "class AddressBuilder:" in result

    def test_reader_has_properties(self, simple_schema_path: Path) -> None:
        """Reader class should have property definitions."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "def name(self) -> str:" in result
        assert "def age(self) -> int:" in result
        assert "def email(self) -> str:" in result

    def test_builder_has_properties_and_setters(self, simple_schema_path: Path) -> None:
        """Builder class should have property definitions with setters."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        # Properties
        assert "@property" in result
        # Setters
        assert "@name.setter" in result

    def test_stub_contains_module_class(self, simple_schema_path: Path) -> None:
        """Generated stub should contain struct module classes."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "class _PersonModule:" in result
        assert "class _AddressModule:" in result

    def test_module_has_factory_methods(self, simple_schema_path: Path) -> None:
        """Module class should have factory methods."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "def new_message() -> PersonBuilder:" in result
        # from_bytes is now a context manager returning Iterator
        assert "def from_bytes(" in result
        assert ") -> Iterator[PersonReader]:" in result
        assert "@contextmanager" in result
        assert "def from_bytes_packed(" in result


class TestStubGeneratorEnumSchema:
    """Tests for generating stubs from a schema with enums."""

    def test_stub_contains_enum_classes(self, enum_schema_path: Path) -> None:
        """Generated stub should contain enum classes."""
        generator = StubGenerator(enum_schema_path)
        result = generator.generate_stub()

        assert "class Color:" in result
        assert "class Status:" in result

    def test_enum_has_enumerants(self, enum_schema_path: Path) -> None:
        """Enum class should have enumerant definitions."""
        generator = StubGenerator(enum_schema_path)
        result = generator.generate_stub()

        assert "red: int" in result
        assert "green: int" in result
        assert "blue: int" in result
        assert "pending: int" in result
        assert "active: int" in result


class TestStubGeneratorListSchema:
    """Tests for generating stubs from a schema with lists."""

    def test_list_types_generated(self, list_schema_path: Path) -> None:
        """List types should be properly generated."""
        generator = StubGenerator(list_schema_path)
        result = generator.generate_stub()

        assert "def names(self) -> list[str]:" in result
        assert "def numbers(self) -> list[int]:" in result
        assert "def flags(self) -> list[bool]:" in result


class TestStubGeneratorComplexSchema:
    """Tests for generating stubs from a complex schema."""

    def test_struct_references_generated(self, complex_schema_path: Path) -> None:
        """Struct references should use Reader/Builder types."""
        generator = StubGenerator(complex_schema_path)
        result = generator.generate_stub()

        # Reader class should reference other Readers
        assert "def assignee(self) -> UserReader:" in result
        # Recursive struct references
        assert "list[TaskReader]" in result or "def subtasks(self)" in result

    def test_enum_references_in_struct(self, complex_schema_path: Path) -> None:
        """Enum references should be properly typed."""
        generator = StubGenerator(complex_schema_path)
        result = generator.generate_stub()

        assert "Priority" in result


class TestStubGeneratorRuntimeModule:
    """Tests for generating runtime modules."""

    def test_generate_runtime_module(self, simple_schema_path: Path) -> None:
        """generate_runtime_module should return valid Python code."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_runtime_module()

        assert isinstance(result, str)
        assert "import capnp as _capnp" in result
        assert "_schema = _capnp.load(" in result

    def test_runtime_module_exports_types(self, simple_schema_path: Path) -> None:
        """Runtime module should export all types."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_runtime_module()

        assert "Person = _schema.Person" in result
        assert "Address = _schema.Address" in result
        assert "__all__" in result

    def test_runtime_module_with_custom_path(self, simple_schema_path: Path) -> None:
        """Runtime module should use custom proto path if provided."""
        generator = StubGenerator(simple_schema_path)
        custom_path = 'str(Path(__file__).parent / "schema.capnp")'
        result = generator.generate_runtime_module(proto_import_path=custom_path)

        assert custom_path in result


class TestStubGeneratorWriteFiles:
    """Tests for writing files to disk."""

    def test_write_files_creates_stub(self, simple_schema_path: Path, temp_dir: Path) -> None:
        """write_files should create a .pyi file."""
        generator = StubGenerator(simple_schema_path)
        output_dir = temp_dir / "output"

        generated = generator.write_files(output_dir)

        stub_path = output_dir / "simple.pyi"
        assert stub_path.exists()
        assert stub_path in generated

    def test_write_files_creates_runtime(self, simple_schema_path: Path, temp_dir: Path) -> None:
        """write_files should create a .py runtime file."""
        generator = StubGenerator(simple_schema_path)
        output_dir = temp_dir / "output"

        generated = generator.write_files(output_dir)

        py_path = output_dir / "simple.py"
        assert py_path.exists()
        assert py_path in generated

    def test_write_files_no_runtime(self, simple_schema_path: Path, temp_dir: Path) -> None:
        """write_files should skip runtime file when requested."""
        generator = StubGenerator(simple_schema_path)
        output_dir = temp_dir / "output"

        generated = generator.write_files(output_dir, generate_runtime=False)

        stub_path = output_dir / "simple.pyi"
        py_path = output_dir / "simple.py"

        assert stub_path.exists()
        assert not py_path.exists()
        assert len(generated) == 1

    def test_write_files_creates_output_dir(self, simple_schema_path: Path, temp_dir: Path) -> None:
        """write_files should create output directory if it doesn't exist."""
        generator = StubGenerator(simple_schema_path)
        output_dir = temp_dir / "nested" / "output" / "dir"

        assert not output_dir.exists()
        generator.write_files(output_dir)
        assert output_dir.exists()


class TestStubGeneratorClassName:
    """Tests for class name generation."""

    def test_make_class_name_simple(self) -> None:
        """Simple schema names should be converted to PascalCase."""
        assert StubGenerator._make_class_name("simple") == "SimpleSchema"

    def test_make_class_name_with_underscores(self) -> None:
        """Underscored names should be converted to PascalCase."""
        assert StubGenerator._make_class_name("my_schema") == "MySchemaSchema"

    def test_make_class_name_with_dashes(self) -> None:
        """Dashed names should be converted to PascalCase."""
        assert StubGenerator._make_class_name("my-schema") == "MySchemaSchema"

    def test_make_class_name_mixed(self) -> None:
        """Mixed separators should be handled."""
        assert StubGenerator._make_class_name("my-complex_schema") == "MyComplexSchemaSchema"


class TestStubGeneratorUnionSchema:
    """Tests for generating stubs with union types and Literal which()."""

    def test_union_which_has_literal_return(self, union_schema_path: Path) -> None:
        """Union structs should have which() returning Literal with field names."""
        generator = StubGenerator(union_schema_path)
        result = generator.generate_stub()

        # Message union should have all 4 fields in Literal
        assert 'def which(self) -> Literal["text", "number", "data", "empty"]' in result

    def test_result_union_which_type(self, union_schema_path: Path) -> None:
        """Result union should have which() with success and error."""
        generator = StubGenerator(union_schema_path)
        result = generator.generate_stub()

        assert 'Literal["success", "error"]' in result


class TestStubGeneratorBuilderMethods:
    """Tests for enhanced Builder class methods."""

    def test_builder_has_to_segments(self, simple_schema_path: Path) -> None:
        """Builder should have to_segments method."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "def to_segments(self) -> list[bytes]:" in result

    def test_builder_has_write_methods(self, simple_schema_path: Path) -> None:
        """Builder should have write and write_packed methods."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "def write(self, file: BufferedWriter) -> None:" in result
        assert "def write_packed(self, file: BufferedWriter) -> None:" in result

    def test_imports_buffered_writer(self, simple_schema_path: Path) -> None:
        """Stub should import BufferedWriter."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "from io import BufferedWriter" in result


class TestStubGeneratorInitOverloads:
    """Tests for typed init() method overloads."""

    def test_init_overloads_for_list_fields(self, complex_schema_path: Path) -> None:
        """Init overloads should be generated for list fields."""
        generator = StubGenerator(complex_schema_path)
        result = generator.generate_stub()

        # Task struct has subtasks (List(Task)) and tags (List(Text))
        assert 'def init(self, name: Literal["subtasks"])' in result
        assert 'def init(self, name: Literal["tags"])' in result
        # Project has tasks (List(Task)) and members (List(User))
        assert 'def init(self, name: Literal["tasks"])' in result
        assert 'def init(self, name: Literal["members"])' in result

    def test_init_fallback_overloads(self, simple_schema_path: Path) -> None:
        """Should always have fallback init overloads with str."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "def init(self, name: str) -> Any:" in result
        assert "def init(self, name: str, size: int) -> Any:" in result


class TestStubGeneratorFromBytesContextManager:
    """Tests for from_bytes as context manager."""

    def test_from_bytes_returns_iterator(self, simple_schema_path: Path) -> None:
        """from_bytes should return Iterator as it's a context manager."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "Iterator[PersonReader]" in result
        assert "@contextmanager" in result

    def test_from_bytes_has_optional_params(self, simple_schema_path: Path) -> None:
        """from_bytes should have traversal_limit and nesting_limit params."""
        generator = StubGenerator(simple_schema_path)
        result = generator.generate_stub()

        assert "traversal_limit_in_words: int | None" in result
        assert "nesting_limit: int | None" in result
